name: P-Data
networks:
  rede_iot:
    external: true

services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'

      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          memory: 256M
    networks:
      - rede_iot

  kafka-connect:
    build: ./config/kafka-connect
    container_name: kafka-connect
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - rede_iot

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:8.2.2
    container_name: ksqldb-server
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    volumes:
      - ./config/ksqldb/queries.sql:/etc/ksqldb/queries.sql:ro
      - ./config/ksqldb/ext/iot-regras-bateria-1.0.0.jar:/etc/ksqldb/ext/iot-regras-bateria-1.0.0.jar
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "kafka:9092"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_HEAP_OPTS: "-Xms512M -Xmx1G"
      KSQL_KSQL_QUERIES_FILE: "/etc/ksqldb/queries.sql"
      KSQL_KSQL_EXTENSION_DIR: "/etc/ksqldb/ext"
      KSQL_KSQL_STREAMS_PROCESSING_GUARANTEE: "exactly_once_v2"
      KSQL_KSQL_STREAMS_COMMIT_INTERVAL_MS: "100"
      KSQL_KSQL_STREAMS_CACHE_MAX_BYTES_BUFFERING: "0"
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - rede_iot

volumes:
  kafka_data:
