[agent]
  interval = "5s"
  flush_interval = "5s"
  omit_hostname = true
  debug = true

# ==========================================
# ENTRADAS (KAFKA)
# ==========================================

# GERAÇÃO
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["iot_geracao"]
  consumer_group = "telegraf_geracao"
  version = "2.8.0"
  data_format = "json"
  name_override = "geracao" # Tabela no InfluxDB
  json_time_key = "timestamp"
  json_time_format = "unix"
  tag_keys = ["id_dispositivo", "categoria"]

  [inputs.kafka_consumer.tags]
    bucket_destino = "telemetria_iot"

# ARMAZENAMENTO
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["iot_armazenamento"]
  consumer_group = "telegraf_armazenamento"
  version = "2.8.0"
  data_format = "json"
  name_override = "armazenamento" # Tabela no InfluxDB
  json_time_key = "timestamp"
  json_time_format = "unix"
  tag_keys = ["id_dispositivo", "categoria"]

# DISPOSITIVOS
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["iot_dispositivos"]
  consumer_group = "telegraf_dispositivos"
  version = "2.8.0"
  data_format = "json"
  name_override = "dispositivo" # Tabela no InfluxDB
  json_time_key = "timestamp"
  json_time_format = "unix"
  tag_keys = ["id_dispositivo", "categoria"]

# 4. TÓPICO: COMANDOS
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["comandos_mqtt_iot"]
  consumer_group = "telegraf_comandos"
  version = "2.8.0"
  name_override = "comandos" # Tabela no InfluxDB
  data_format = "json"
  tag_keys = ["CATEGORIA", "COMANDO"]

# ==========================================
# SAÍDAS (INFLUXDB)
# ==========================================

# DESTINO - TELEMETRIA e COMANDOS - INFLUXDB
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"