[agent]
  interval = "5s"
  flush_interval = "5s"
  omit_hostname = true
  debug = true

# ==========================================
# ENTRADAS (KAFKA)
# ==========================================

# TÓPICO TELEMETRIA-IOT DO KAFKA
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["telemetria_iot"]
  consumer_group = "telegraf_telemetria"
  version = "2.8.0"
  data_format = "json"
  name_override = "iot_sensor"
  json_time_key = "timestamp"
  json_time_format = "unix"
  tag_keys = ["id_dispositivo"]

  # ETiqueta necessária para o roteamento do InfluxDB
  [inputs.kafka_consumer.tags]
    bucket_destino = "telemetria_iot"


# TÓPICO COMANDOS_FINAIS_DISPOSITIVOS DO KAFKA
[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["comandos_mqtt_iot"]
  consumer_group = "telegraf_comandos"
  version = "2.8.0"
  data_format = "json"
  tag_keys = ["CATEGORIA", "COMANDO"]

  # Etiqueta dos dados de telemetria no bucket
  [inputs.kafka_consumer.tags]
    bucket_destino = "comandos_mqtt_iot"

# ==========================================
# SAÍDAS (INFLUXDB)
# ==========================================

# DESTINO - TELEMETRIA - INFLUXDB
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

  [outputs.influxdb_v2.tagpass]
    bucket_destino = ["telemetria_iot"]

# DESTINO - COMANDOS - INFLUXDB
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"

    # Etiqueta dos dados de comandos no bucket
  [outputs.influxdb_v2.tagpass]
    bucket_destino = ["comandos_mqtt_iot"]